### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by jimgus** [XenitAB/xkf-templates#16]
The code in this repository refers to Terraform modules in https://github.com/XenitAB/terraform-modules. Discover the possibilities to trigger a Github action when a new release of https://github.com/XenitAB/terraform-modules is made, update the code according to the new version. If possible and if not too much work, automatically create a new release if the checks are passing. Alternatively, create a PR.

**Comment by NissesSenap** [comment]
This have been implemented.
