### ISSUE TITLE
Sync pipelines

### ISSUE THREAD

**Issue by jimgus** [XenitAB/xkf-templates#31]
As of now only the upgrade pipeline synced to the instance repositories. We would like to do the same for remaining pipelines for the different Terraform states. The pipelines do however need to be parameterized since there are differences between the instance repositories. The following parameters are needed:

- environments
- poolNameTemplate (Azure devops only)

This can be done by using:

- https://techgenix.com/environment-as-variables-in-your-azure-devops-pipelines/ (Azure Devops)
- https://github.com/marketplace/actions/dotenv-action (Github Actions)

**Comment by jimgus** [comment]
Github Actions Done!

**Comment by landerss1** [comment]
This repo will bee archived.
